// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// prettier-ignore
const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:8e6f2412-cec8-45a3-be8c-af4932eaa5c6",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_K1CO1u11d",
    "aws_user_pools_web_client_id": "65bn6c37sq6947ki0c8ch9vss8",
    "oauth": {
        "domain": "gpadmin-prod-auth.auth.ap-northeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost/",
        "redirectSignOut": "http://localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "gpadmin-prod-api-v1",
            "endpoint": "https://4za64xeik1.execute-api.ap-northeast-2.amazonaws.com/prod/v1/api",
            "region": "ap-northeast-2"
        },
        {
            "name": "gpadmin-prod-cdn-v1",
            "endpoint": "https://4za64xeik1.execute-api.ap-northeast-2.amazonaws.com/prod/v1/cdn",
            "region": "ap-northeast-2"
        },
        {
            "name": "gpadmin-prod-noneauth-v1",
            "endpoint": "https://4za64xeik1.execute-api.ap-northeast-2.amazonaws.com/prod/v1/noneauth",
            "region": "ap-northeast-2"
        },
        {
            "name": "gpadmin-prod-cms-v1",
            "endpoint": "https://4za64xeik1.execute-api.ap-northeast-2.amazonaws.com/prod/v1/cms",
            "region": "ap-northeast-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://kgvqpi76zjclhh45rl5eo3s47m.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "gp-prod-file",
    "aws_user_files_s3_bucket_region": "ap-northeast-2",
    "aws_content_delivery_bucket": "gp-prod-cms",
    "aws_content_delivery_bucket_region": "ap-northeast-2",
    "aws_content_delivery_url": "gp-prod-src"
};
export default awsmobile;
